### ISSUE TITLE
LZ point coordinate export error

### ISSUE THREAD

**Issue by Majpuc** [Neural-Systems-at-UIO/LocaliZoom#39] opened 2023-04-24 11:31 UTC
When exporting coordinates, the xlsx sheet only displays "undefined" cells

**Comment by Tevemadar** [comment] 2023-04-24 14:29
Duplicate of https://github.com/Neural-Systems-at-UIO/LocaliZoom/issues/38

**Closed by Tevemadar** 2023-04-24 14:29 UTC
Labels: bug
